Rename packages and add license
osukhoroslov/sim-project pull request #82
Opened 2022-06-13 16:40 UTC by osukhoroslov

2022-06-13 23:01 UTC, maksim1744 approved these changes

2022-06-14 19:15 UTC, SYury requested changes

2022-06-14 19:15 UTC, SYury commented on examples/faas-in-the-wild/Cargo.toml
> +name = "faas-in-the-wild"
Мне не нравится такое переименование, serverless in the wild это название статьи, которая тут воспроизводится, а вот faas in the wild это уже нечто непонятное. Если хочется, чтобы в названиях всех faas-примеров было слово faas, предлагаю назвать это faas-serverless-in-the-wild.

2022-06-14 20:55 UTC, kuskarov approved these changes

2022-06-14 22:10 UTC, kuskarov commented
Предлагаю сначала влить [мой PR](https://github.com/osukhoroslov/sim-project/pull/68). Там вроде бы готово все.

2022-06-15 20:03 UTC, osukhoroslov commented on examples/faas-in-the-wild/Cargo.toml
> +name = "faas-in-the-wild"
Вернул serverless-in-the-wild

2022-06-15 20:10 UTC, SYury approved these changes

2022-06-17 10:53 UTC, merged